added test_tags.py, extended utils.py/Endpoint class with put method
Tracardi/tracardi-integration-tests pull request #1
Opened 2021-11-17 17:09 UTC by DawidekZagajnik

2021-11-18 11:19 UTC, atompie requested changes

2021-11-18 11:19 UTC, atompie commented on tracardi_tests/api/test_tags.py
> +def create_request(tags: List[str], event_type: str):
we prefix each function with test_ this way if something fails we will know in what function it happened.

2021-11-18 19:06 UTC, DawidekZagajnik commented on tracardi_tests/api/test_tags.py
> +def create_request(tags: List[str], event_type: str):
done

2021-11-19 00:23 UTC, atompie approved these changes

2021-11-19 00:23 UTC, closed without merging